# Generated by Django 6.0 on 2026-03-17 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address_hash', models.CharField(db_index=True, max_length=64)),
                ('user_agent', models.CharField(max_length=512)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(blank=True, max_length=50, null=True)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='core.qrcode')),
            ],
            options={
                'verbose_name': 'Scan Analytics',
                'verbose_name_plural': 'Scan Analytics',
                'ordering': ['-timestamp'],
            },
        ),
    ]
